---
# Per environment values which override defaults in hmpps-pecs-profile-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-pecs-profile-ui-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-pecs-profile-ui-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-pecs-profile-ui-non-prod
